### ISSUE TITLE
Call to undefined function EllipticCurve\Utils\gmp_init()

### ISSUE THREAD

**Issue by rodrigopaggue** [starkbank/sdk-php#66]
Atualizando para essa nova versão do Sdk e estou recebendo o seguinte erro

`

Call to undefined function EllipticCurve\Utils\gmp_init()
--

`

**Comment by jerowork** [comment]
@rodrigopaggue this is 'solved' with https://github.com/starkbank/ecdsa-php/pull/18.

You need to install GMP (see https://www.php.net/manual/en/gmp.installation.php)
